project:
  type: website

website:
  title: "Iacopo Ferrario"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css

# code executed only locally
execute:
  freeze: auto
