name: deploy-website

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pag_url }}
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    
    # Build the pages
    # - name: Build the site
    #   run: |
    #     make html
    #     #    - name: Upload Artifacts
    #     #      uses: actions/upload-pages-artifact@v1
    #     #      with:
    #     #        path: ./dist
    
    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # # If we've pushed to main, push the book's HTML to github-pages
    # - if: ${{ github.ref == 'refs/heads/main' }}
    #   name: GitHub Pages action
    #     #id: deployment
    #     #uses: actions/deploy-pages@v1        
    #   uses: peaceiris/actions-gh-pages@v3.5.9
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./_build/html
    #     cname: iacopoff.github.io


