name: deploy-website

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pag_url }}
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    # Build the pages
    - name: Build the site
      run: |
        make html
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist
    # If we've pushed to main, push the book's HTML to github-pages
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: GitHub Pages action
      id: deployment
      uses: actions/deploy-pages@v1

       
        
        #uses: peaceiris/actions-gh-pages@v3.5.9
        #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #publish_dir: ./_build/html
        #cname: iacopoferrario.com


